// <auto-generated />
using System;
using CelebrancyHQ.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CelebrancyHQ.Entities.Migrations
{
    [DbContext(typeof(CelebrancyHQContext))]
    [Migration("20221004120710_UpdateDescriptionOnCeremonyFilesToBeNullable")]
    partial class UpdateDescriptionOnCeremonyFilesToBeNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CelebrancyHQ.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Auditing.CeremonyAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("PersonId");

                    b.ToTable("CeremonyAuditLogs");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Auditing.OrganisationAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("PersonId");

                    b.ToTable("OrganisationAuditLogs");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Auditing.PersonAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PersonAuditLogs");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Ceremony", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CeremonyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CeremonyTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeId");

                    b.ToTable("Ceremonies");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyAccessInvitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("PersonId");

                    b.ToTable("CeremonyAccessInvitations");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyTypeDateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("CeremonyTypeDateId");

                    b.ToTable("CeremonyDates");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("FileId");

                    b.ToTable("CeremonyFiles");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyTypeMeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("CeremonyTypeMeetingId");

                    b.ToTable("CeremonyMeetings");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeetingParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyMeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyMeetingId");

                    b.HasIndex("PersonId");

                    b.ToTable("CeremonyMeetingParticipants");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeetingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CeremonyMeetingId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyTypeMeetingQuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyMeetingId");

                    b.HasIndex("CeremonyTypeMeetingQuestionId");

                    b.ToTable("CeremonyMeetingQuestions");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeetingQuestionFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("QuestionId");

                    b.ToTable("CeremonyMeetingQuestionFiles");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyTypeParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("CeremonyTypeParticipantId");

                    b.HasIndex("PersonId");

                    b.ToTable("CeremonyParticipants");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEditWithApproval")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewHistory")
                        .HasColumnType("bit");

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyTypeParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApprover")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("CeremonyTypeParticipantId");

                    b.ToTable("CeremonyPermissions");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<int>("CeremonyTypeServiceProviderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("CeremonyTypeServiceProviderId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("CeremonyServiceProviders");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("CeremonyTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Marriage",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A ceremony to celebrate the joining of two persons in marriage.",
                            Name = "Marriage Ceremony",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "Funeral",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A ceremony to celebrate the life of and remember a person who has recently passed way.",
                            Name = "Funeral Ceremony",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeId");

                    b.ToTable("CeremonyTypeDates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CeremonyTypeId = 1,
                            Code = "InitialPhoneCall",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Initial phone call",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CeremonyTypeId = 1,
                            Code = "InitialInterview",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Initial interview",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CeremonyTypeId = 1,
                            Code = "Rehearsal",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Rehearsal",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CeremonyTypeId = 1,
                            Code = "Ceremony",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Ceremony",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CeremonyTypeId = 1,
                            Code = "Reception",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Reception",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CeremonyTypeId = 1,
                            Code = "Other",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Other",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CeremonyTypeId = 2,
                            Code = "InitialPhoneCall",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Initial phone call",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CeremonyTypeId = 2,
                            Code = "InitialInterview",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Initial interview",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CeremonyTypeId = 2,
                            Code = "Rehearsal",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Rehearsal",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CeremonyTypeId = 2,
                            Code = "Ceremony",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Ceremony",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CeremonyTypeId = 2,
                            Code = "Wake",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Wake",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CeremonyTypeId = 2,
                            Code = "Other",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Other",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CeremonyTypeId = 2,
                            Code = "Death",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Death",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeFileCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeId");

                    b.ToTable("CeremonyTypeFileCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CeremonyTypeId = 1,
                            Code = "Meeting",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "A meeting with another ceremony participant.",
                            Name = "Meeting",
                            PermissionCode = "Meeting",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CeremonyTypeId = 2,
                            Code = "Meeting",
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Description = "A meeting with another ceremony participant.",
                            Name = "Meeting",
                            PermissionCode = "Meeting",
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeMeeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TemplateId");

                    b.ToTable("CeremonyTypeMeetings");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeMeetingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyTypeMeetingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeMeetingId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("CeremonyTypeMeetingQuestions");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeMeetingQuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CeremonyTypeMeetingQuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Text",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A field that can accept text or HTML data.",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "Dropdown",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A field that allows the user to select one option from a list.",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "Checkboxes",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A field that allows the user to select zero or more options from a row of checkboxes.",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Code = "Image",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A field that allows the user to select an image.",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Code = "File",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A field that allows the user to select a file.",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaximumNumberOfParticipants")
                        .HasColumnType("int");

                    b.Property<int?>("MinimumNumberOfParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAddress")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPhoneNumber")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeId");

                    b.ToTable("CeremonyTypeParticipants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CeremonyTypeId = 1,
                            Code = "Celebrant",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 1,
                            MinimumNumberOfParticipants = 1,
                            Name = "Celebrant",
                            RequiresAddress = true,
                            RequiresPhoneNumber = true,
                            SortOrder = 1,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CeremonyTypeId = 2,
                            Code = "Celebrant",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 1,
                            MinimumNumberOfParticipants = 1,
                            Name = "Celebrant",
                            RequiresAddress = true,
                            RequiresPhoneNumber = true,
                            SortOrder = 1,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CeremonyTypeId = 1,
                            Code = "Couple",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 2,
                            MinimumNumberOfParticipants = 2,
                            Name = "Couple",
                            RequiresAddress = true,
                            RequiresPhoneNumber = true,
                            SortOrder = 2,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CeremonyTypeId = 1,
                            Code = "Organiser",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Organiser",
                            RequiresAddress = true,
                            RequiresPhoneNumber = true,
                            SortOrder = 3,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CeremonyTypeId = 2,
                            Code = "Organiser",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MinimumNumberOfParticipants = 1,
                            Name = "Organiser",
                            RequiresAddress = true,
                            RequiresPhoneNumber = true,
                            SortOrder = 3,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CeremonyTypeId = 1,
                            Code = "Witness",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 2,
                            MinimumNumberOfParticipants = 2,
                            Name = "Witness",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 4,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CeremonyTypeId = 1,
                            Code = "BridalParty",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Bridal party",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 5,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CeremonyTypeId = 1,
                            Code = "InvitedGuest",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Invited guest",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 7,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CeremonyTypeId = 2,
                            Code = "Deceased",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 1,
                            MinimumNumberOfParticipants = 1,
                            Name = "Deceased person",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 2,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CeremonyTypeId = 2,
                            Code = "InvitedGuest",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Invited guest",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 6,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CeremonyTypeId = 1,
                            Code = "Other",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Other",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 8,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CeremonyTypeId = 2,
                            Code = "Other",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Other",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 7,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CeremonyTypeId = 1,
                            Code = "Interpreter",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 1,
                            Name = "Interpreter",
                            RequiresAddress = false,
                            RequiresPhoneNumber = false,
                            SortOrder = 6,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CeremonyTypeId = 2,
                            Code = "Interpreter",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            MaximumNumberOfParticipants = 1,
                            Name = "Interpreter",
                            RequiresAddress = false,
                            RequiresPhoneNumber = true,
                            SortOrder = 5,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CeremonyTypeId = 2,
                            Code = "FuneralDirector",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Funeral director",
                            RequiresAddress = true,
                            RequiresPhoneNumber = true,
                            SortOrder = 4,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyTypeId");

                    b.ToTable("CeremonyTypeServiceProviders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CeremonyTypeId = 1,
                            Code = "Photographer",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Photographer",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CeremonyTypeId = 2,
                            Code = "Photographer",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Photographer",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CeremonyTypeId = 1,
                            Code = "Videographer",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Videographer",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CeremonyTypeId = 2,
                            Code = "Videographer",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Videographer",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CeremonyTypeId = 1,
                            Code = "Musician",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Musician",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CeremonyTypeId = 2,
                            Code = "Musician",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Musician",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CeremonyTypeId = 1,
                            Code = "Caterer",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Caterer",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CeremonyTypeId = 2,
                            Code = "Caterer",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Caterer",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CeremonyTypeId = 1,
                            Code = "Calligrapher",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Calligrapher",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CeremonyTypeId = 2,
                            Code = "Calligrapher",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Calligrapher",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CeremonyTypeId = 1,
                            Code = "Florist",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Florist",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CeremonyTypeId = 2,
                            Code = "Florist",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Florist",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CeremonyTypeId = 2,
                            Code = "FuneralDirector",
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Name = "Funeral Director",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyVenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CeremonyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CeremonyId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("CeremonyVenues");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.File", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Organisation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Organisations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            EmailAddress = "info@celebrancyhq.co",
                            Name = "CelebrancyHQ",
                            Type = "Celebrant",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Website = "https://www.celebrancyhq.co"
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.OrganisationPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("OrganisationPhoneNumbers");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganisationId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Registered")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("OrganisationId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            EmailAddress = "system.admin@celebrancyhq.co",
                            FirstName = "CelebrancyHQ",
                            Gender = "Other",
                            LastName = "System Administrator",
                            PreferredName = "System Administrator",
                            Registered = true,
                            Title = "Mx",
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.PersonPhoneNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonPhoneNumbers");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            EmailAddress = "system.admin@celebrancyhq.co",
                            PasswordHash = "testpassword",
                            PasswordSalt = "passwordsalt",
                            PersonId = 0,
                            Updated = new DateTime(2022, 5, 8, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Auditing.CeremonyAuditLog", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Auditing.OrganisationAuditLog", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Auditing.PersonAuditLog", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Person", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Ceremony", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyType", "CeremonyType")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyType");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyAccessInvitation", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyDate", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeDate", "CeremonyTypeDate")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeDateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("CeremonyTypeDate");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyFile", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeFileCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Ceremony");

                    b.Navigation("File");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeeting", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeMeeting", "CeremonyTypeMeeting")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("CeremonyTypeMeeting");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeetingParticipant", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyMeeting", "CeremonyMeeting")
                        .WithMany()
                        .HasForeignKey("CeremonyMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyMeeting");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeetingQuestion", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyMeeting", "CeremonyMeeting")
                        .WithMany()
                        .HasForeignKey("CeremonyMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeMeetingQuestion", "CeremonyTypeMeetingQuestion")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeMeetingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyMeeting");

                    b.Navigation("CeremonyTypeMeetingQuestion");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyMeetingQuestionFile", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyFile", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyMeetingQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyParticipant", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeParticipant", "CeremonyTypeParticipant")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("CeremonyTypeParticipant");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyPermission", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeParticipant", "CeremonyTypeParticipant")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("CeremonyTypeParticipant");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyServiceProvider", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeServiceProvider", "CeremonyTypeServiceProvider")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeServiceProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("CeremonyTypeServiceProvider");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyType", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeDate", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyType", "CeremonyType")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyType");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeFileCategory", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyType", "CeremonyType")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyType");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeMeeting", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyType", "CeremonyType")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId");

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeMeeting", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId");

                    b.Navigation("CeremonyType");

                    b.Navigation("Organisation");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeMeetingQuestion", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeMeeting", "CeremonyTypeMeeting")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.CeremonyTypeMeetingQuestionType", "QuestionType")
                        .WithMany()
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyTypeMeeting");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeParticipant", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyType", "CeremonyType")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyType");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyTypeServiceProvider", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.CeremonyType", "CeremonyType")
                        .WithMany()
                        .HasForeignKey("CeremonyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeremonyType");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.CeremonyVenue", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Ceremony", "Ceremony")
                        .WithMany()
                        .HasForeignKey("CeremonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ceremony");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.File", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Person", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Organisation", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.OrganisationPhoneNumber", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.Person", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("CelebrancyHQ.Entities.Organisation", "Organisation")
                        .WithMany()
                        .HasForeignKey("OrganisationId");

                    b.Navigation("Address");

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.PersonPhoneNumber", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CelebrancyHQ.Entities.User", b =>
                {
                    b.HasOne("CelebrancyHQ.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });
#pragma warning restore 612, 618
        }
    }
}
